site_name: Abot Docs
use_directory_urls: true

nav:
  - Home: '/index.md'
  - Installation: '/installation.md'
  - Quick start:
      - 'Hello world': '/quick_start/hello_world.md'
      - 'Views': '/quick_start/fronted/views.md'