site_name: Abot Docs
copyright: Copyright©2020, Maintained by the Abot Team.
theme:
    name: material
    language: zh
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
nav:
  - 安装: 'installation.md'
  - 快速开始: 'quickstart.md'
  - 前端开发:
      - '视图': 'fronted/views.md'
  - 后端开发:
      - '发布': 'backend/publish.md'
